image: jangrewe/gitlab-ci-android

stages:
  - build

variables:
  ANDROID_SDK_ROOT: /Library/Android/sdk
  KEYSTORE_ALIAS: key0
  KEYSTORE_PASSWORD: newapp
  KEY_PASSWORD: newapp
  APPLICATION_ID: com.Land.Adventures.Alaska.nature.app
  TELEGRAM_BOT_TOKEN: 6667949208:AAEz2A6DWM4n805sY_O6ycQ5CufDFQU04Dk  # Замените на токен вашего бота
  TELEGRAM_CHAT_ID: -4031862147
  KEYPASS_FILE: keystore.pass
  KEYSTORE_FILE: keystore.jks


before_script:
  - |
    if ! command -v flutter &> /dev/null
    then
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
    fi


build:
  stage: build
  script:
    - |
      KEYSTORE_FILE=$CI_PROJECT_DIR/android/app/keystore.jks
      
      if [ -f $KEYSTORE_FILE ]; then
      echo "File $KEYSTORE_FILE already exists."
      else
      keytool -genkeypair -v -keystore $KEYSTORE_FILE -keyalg RSA -keysize 2048 -validity 10000 -alias $KEYSTORE_ALIAS -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD -dname "CN=John Doe, OU=Dev, O=Company, L=City, ST=State, C=US"
      echo "Created $KEYSTORE_FILE in the app directory."
      fi
      
      flutter packages get
      flutter build appbundle --release --obfuscate --split-debug-info=$CI_PROJECT_DIR
      flutter build apk --release --obfuscate --split-debug-info=$CI_PROJECT_DIR
      mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/$APPLICATION_ID.apk
      mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/$APPLICATION_ID.aab

  artifacts:
    name: $APPLICATION_ID
    paths:
      - build/app/outputs/flutter-apk/$APPLICATION_ID.apk
      - build/app/outputs/bundle/release/$APPLICATION_ID.aab
      - $CI_PROJECT_DIR/android/app/keystore.jks

  only:
    - master
after_script:
  - |
    # Отправляем сообщение с комментарием коммита в Telegram бота
    MESSAGE="$CI_COMMIT_MESSAGE"
    curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"

    # Отправка артефактов и ключевого хранилища в Telegram бота
    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@build/app/outputs/flutter-apk/$APPLICATION_ID.apk -F text=MESSAGE -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@build/app/outputs/bundle/release/$APPLICATION_ID.aab -F text=MESSAGE -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@android/app/keystore.jks -F text="Keystore File" -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
